"use client";
import {useEffect,useState} from 'react';
import type {CSSProperties} from 'react';
import type {Account} from './account-client';
import {Button} from './ui-button';
import {ImageReader} from './library-workspace';
import {learningRecords,wrongQuestions,abilityEvidence} from '../lib/learning-records.mjs';
type Records=ReturnType<typeof learningRecords>;
export default function LearningWorkspace({user,wrong=false,ability=false}:{user:Account;wrong?:boolean;ability?:boolean}){
 const [records,setRecords]=useState<Records>([]),[error,setError]=useState(''),[source,setSource]=useState(''),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[selected,setSelected]=useState('');
 useEffect(()=>{const refresh=()=>{try{setRecords(learningRecords(localStorage,user));setError('');}catch(e){setError((e as Error).message);}};refresh();window.addEventListener('storage',refresh);window.addEventListener('focus',refresh);return()=>{window.removeEventListener('storage',refresh);window.removeEventListener('focus',refresh);};},[user.id]);
 const match=(r:{source:string;title:string;time:string})=>(!source||r.source===source)&&r.title.includes(query)&&(!from||Date.parse(r.time)>=Date.parse(from+'T00:00:00'))&&(!to||Date.parse(r.time)<=Date.parse(to+'T23:59:59.999'));
 const evidence=abilityEvidence(records),eligible=ability?evidence.flatMap(group=>group.records):records;
 const rows=eligible.filter(match).sort((a,b)=>Date.parse(b.time)-Date.parse(a.time)),errors=wrongQuestions(eligible).filter(match),record=eligible.find(r=>r.id===selected),wrongItem=errors.find(q=>q.key===selected);
 const detail=wrong?wrongItem?{title:wrongItem.prompt,version:wrongItem.version,versionLabel:wrongItem.versionLabel,reason:wrongItem.reason,items:[wrongItem]}:null:record;
 return <section className="question-bank"><header className="library-header">{selected&&<Button className="page-back" onClick={()=>setSelected('')}><span aria-hidden="true">←</span> 返回列表</Button>}<h1>{ability?'能力分析':wrong?'错题集':'学习记录'}</h1></header>{error&&<p role="alert" className="account-error">{error}</p>}
 {ability&&!selected&&<><div className="ability-summary">{evidence.map(group=><article className="account-card" key={group.source}><h2>{group.source==='practice'?'日常练习':'已发布考试'}</h2><p>{group.completed} 条记录 · {group.questions} 道题 · {group.wrong} 道单选错题</p></article>)}</div><details className="account-card"><summary>五维能力 · 尚未评估</summary><p>临床信息理解、关键区域识别、形态学判断、诊断与鉴别、辅助检查决策。评价规则待确认，以下展示已有作答证据。</p></details><h2>作答证据</h2></>}
 {!selected?<><div className="library-toolbar"><label>搜索<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="题目或考试名称"/></label><label>来源<select value={source} onChange={e=>setSource(e.target.value)}><option value="">全部来源</option><option value="practice">日常练习</option><option value="exam">模拟考试</option></select></label><label>开始日期<input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label>结束日期<input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label><Button onClick={()=>{setSource('');setQuery('');setFrom('');setTo('');}}>清空筛选</Button></div>{from&&to&&from>to&&<p role="alert" className="account-error">开始日期不能晚于结束日期。</p>}{wrong?<>{!errors.length&&<p className="account-card">{source||query||from||to?'没有匹配的错题，请调整或清空筛选。':'暂无已确定的错题。'}</p>}{errors.length>0&&<div className="data-table" style={{'--cols':'minmax(0,3fr) .7fr 1.1fr 1fr auto'} as CSSProperties}><div className="head"><span>题目</span><span>来源</span><span>部位</span><span>版本</span><span>操作</span></div>{errors.map(q=><div key={q.key}><span><b>{q.prompt}</b></span><span>{q.source==='practice'?'练习':'考试'}</span><span>{q.organ}</span><span>{q.versionLabel} {q.version}</span><Button onClick={()=>setSelected(q.key)}>查看答案与图片</Button></div>)}</div>}<p className="library-muted">简答错误点归集待评分规则接入，未评分不计作错误。</p></>:<>{!rows.length&&<p className="account-card">{source||query||from||to?'没有匹配的学习记录，请调整或清空筛选。':'暂无学习记录。'}</p>}{rows.length>0&&<div className="data-table" style={{'--cols':'minmax(0,2.6fr) .8fr 1.3fr .6fr auto'} as CSSProperties}><div className="head"><span>题目／考试</span><span>来源</span><span>时间</span><span>得分</span><span>操作</span></div>{rows.map(r=><div key={r.id}><span><b>{r.title}</b><small>{r.state}</small></span><span>{r.source==='practice'?'日常练习':'模拟考试'}</span><span>{new Date(r.time).toLocaleString()}</span><span>{r.total!==null?`${r.total}分`:'—'}</span><Button onClick={()=>setSelected(r.id)}>查看记录</Button></div>)}</div>}</>}</>:detail?<section><h2>{detail.title}</h2><p>{detail.versionLabel} {detail.version}{detail.reason?' · 更正原因：'+detail.reason:''}</p>{!detail.items.length&&<p className="account-card">此考试尚无已发布结果，请在考试中心查看作答或提交状态。</p>}{detail.items.map((q:{id:string;prompt:string;answer:string;reference:string;explanation:string;comment:string;image:string;history:string;score:number|null;maxScore:number|null;questionVersion:number|null},index:number)=><details className="account-card" key={q.id} open={detail.items.length===1}><summary>第{index+1}题 · {q.prompt}{q.score!==null?` · ${q.score}/${q.maxScore}分`:''}</summary>{q.questionVersion!==null&&<p>题目版本 {q.questionVersion}</p>}<h4>本人原答</h4><p className="pre-wrap">{q.answer||'未作答'}</p><h4>参考与解析</h4><p className="pre-wrap">{q.reference}</p><p className="pre-wrap">{q.explanation}</p>{q.comment&&<p>教师点评：{q.comment}</p>}<details><summary>查看当次病例与图片</summary><p>{q.history}</p>{q.image?<ImageReader images={[q.image]}/>:<p>当次未保存图片。</p>}</details></details>)}</section>:<p>此记录已更新，请返回列表。</p>}
 </section>;
}
