"use client";
import {useEffect,useRef,useState} from 'react';
import type {Account} from './account-client';
import {Button} from './ui-button';
import {AnswerEditor} from './answer-editor';
import {useAnswerPart} from './use-answer-part';
import {ImageReader} from './library-workspace';
import {availablePractice,readPractice,seedQuestions,submitPractice} from '../lib/practice.mjs';
import {questionKey} from '../lib/question-bank.mjs';
type Item={id:string;revision:number;type:string;prompt:string;options:{id:string;text:string}[];caseTitle:string;organ:string;history:string;image:string;simulated?:boolean};
type Result={questionId:string;revision:number;answer:string;correct:boolean|null;submittedAt:string;question:{correctId:string;options:{id:string;text:string}[];explanation:string;reference:string}};
export default function PracticeWorkspace({user}:{user:Account}){
 const [items,setItems]=useState<Item[]>([]),[records,setRecords]=useState<Result[]>([]),[selected,setSelected]=useState<Item|null>(null),[answer,setAnswer]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[query,setQuery]=useState(''),[type,setType]=useState('');
 const [saveFailed,setSaveFailed]=useState(false);
 const activeKey='path-edu-practice-active-'+user.id;
 const viewKey=`path-edu-practice-view-${user.id}-${selected?.id||'list'}-${selected?.revision||0}`;
 const [part,setPart,partError]=useAnswerPart(viewKey+'-part');
 useEffect(()=>{const leave=(e:Event)=>{if(saveFailed&&!window.confirm('答案保存失败，请先重试或复制答案。仍要放弃未保存内容并离开？'))e.preventDefault();};const unload=(e:BeforeUnloadEvent)=>{if(saveFailed){e.preventDefault();e.returnValue='';}};window.addEventListener('edu-before-leave',leave);window.addEventListener('beforeunload',unload);return()=>{window.removeEventListener('edu-before-leave',leave);window.removeEventListener('beforeunload',unload);};},[saveFailed]);
 const input=useRef<HTMLTextAreaElement>(null);
 function refresh(){try{const available=availablePractice(seedQuestions(localStorage));setItems(available);setRecords(readPractice(localStorage,user));return available;}catch(e){setError((e as Error).message);}}
 useEffect(()=>{const available=refresh();try{const prior=JSON.parse(sessionStorage.getItem(activeKey)||'null');const q=available?.find((q:Item)=>q.id===prior?.id&&q.revision===prior?.revision);if(q)open(q);}catch{setError('当前练习恢复失败，答案未覆盖');}const listener=(e:StorageEvent)=>{if(e.key===questionKey)refresh();};window.addEventListener('storage',listener);return()=>window.removeEventListener('storage',listener);},[user.id]);
 const draftKey=(q:Item)=>`path-edu-practice-draft-${user.id}-${q.id}-${q.revision}`;
 const result=selected?records.find(r=>r.questionId===selected.id&&r.revision===selected.revision):undefined;
 function open(q:Item){try{const r=readPractice(localStorage,user).find((r:Result)=>r.questionId===q.id&&r.revision===q.revision);setAnswer(r?.answer||localStorage.getItem(draftKey(q))||'');setSelected(q);setSaveFailed(false);setError('');setNotice('');sessionStorage.setItem(activeKey,JSON.stringify({id:q.id,revision:q.revision}));}catch{setError('草稿读取失败，未覆盖数据');}}
 function saveDraft(value:string){if(!selected)return;try{localStorage.setItem(draftKey(selected),value);setSaveFailed(false);setNotice('已保存到本机');setError('');}catch{setSaveFailed(true);setNotice('');setError('答案尚未保存，请重试或复制答案后再离开');}}
 function change(value:string){if(!selected||result)return;setAnswer(value);saveDraft(value);}
 function submit(){if(!selected)return;try{const record=submitPractice(localStorage,user,selected,answer);setRecords(list=>[...list.filter(r=>r.questionId!==record.questionId||r.revision!==record.revision),record]);setError('');setSaveFailed(false);setNotice('已提交');}catch(e){setError((e as Error).message);}}
 const filtered=items.filter(q=>(!type||q.type===type)&&`${q.prompt} ${q.organ} ${q.caseTitle}`.includes(query));
 return <section><header className="library-header"><h1>{selected?'日常练习 · 作答':'日常练习'}</h1>{selected&&<Button onClick={()=>{if(saveFailed&&!window.confirm('答案保存失败，确认放弃未保存内容并返回？'))return;try{sessionStorage.removeItem(activeKey);}catch{setError('练习位置清理失败');}setSelected(null);setSaveFailed(false);refresh();}}>返回练习列表</Button>}</header>{error&&<p role="alert" className="account-error">{error}</p>}{partError&&<p role="status">{partError}</p>}{notice&&<p role="status">{notice}</p>}{saveFailed&&<div className="question-actions"><Button onClick={()=>saveDraft(answer)}>重试保存答案</Button><Button onClick={()=>{input.current?.focus();input.current?.select();}}>选中答案以复制</Button></div>}
 {!selected?<><div className="library-toolbar"><label>搜索练习<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="题目、病例或部位"/></label><label>题型<select value={type} onChange={e=>setType(e.target.value)}><option value="">全部</option><option value="single">单选</option><option value="short">简答</option></select></label></div>{!filtered.length&&<p className="account-card">暂无已开放练习。</p>}{filtered.map(q=><article className="account-card" key={q.id}><h2>{q.prompt}</h2><p>{q.caseTitle} · {q.type==='single'?'单选':'简答'} · v{q.revision}</p><Button variant="primary" onClick={()=>open(q)}>{records.some(r=>r.questionId===q.id&&r.revision===q.revision)?'查看本次作答':'开始练习'}</Button></article>)}</>:<><nav className="practice-tabs" aria-label="练习内容">{[['history','临床资料'],['image','图片'],['answer','作答与解析']].map(([id,label])=><Button key={id} aria-pressed={part===id} onClick={()=>setPart(id)}>{label}</Button>)}</nav><div className={"practice-columns practice-show-"+part}><aside className="account-card"><h2>临床资料</h2><h3>{selected.caseTitle}</h3><p>{selected.organ}</p><p className="pre-wrap">{selected.history}</p>{selected.simulated&&<span className="library-tag">模拟素材</span>}</aside><ImageReader key={viewKey} stateKey={viewKey} images={[selected.image]}/><section className="account-card question-bank"><h2>{result?'答案与解析':'作答'}</h2><p>{selected.prompt}</p>{selected.type==='single'?selected.options.map(o=><label key={o.id}><input type="radio" name="practice-answer" disabled={Boolean(result)} checked={(result?.answer||answer)===o.id} onChange={()=>change(o.id)}/>{o.text}</label>):<AnswerEditor key={viewKey} inputRef={input} label="简答答案" disabled={Boolean(result)} value={result?.answer||answer} onChange={change}/>}
 {!result?<Button variant="primary" disabled={!answer.trim()} onClick={submit}>提交本题</Button>:<><h3>{result.correct===null?'教师参考':result.correct?'回答正确':'回答不正确'}</h3><p className="pre-wrap">{selected.type==='single'?result.question.options.find(o=>o.id===result.question.correctId)?.text:result.question.reference}</p>{selected.type==='single'&&<p>{result.question.explanation}</p>}<details><summary>AI追问</summary><p>AI服务尚未接入。当前可查看教师预设解析。</p><textarea aria-label="AI追问" disabled placeholder="接入后可就本题追问"/><Button disabled>发送</Button></details></>}
 </section></div></>}</section>;
}
