"use client";
import {useEffect,useRef,useState} from 'react';
import type {CSSProperties} from 'react';
import type {Account} from './account-client';
import {Button} from './ui-button';
import {readLibraryStore,visibleLibraryCases,libraryCategories} from '../lib/library.mjs';
import {releasedQuestions,saveQuestion,setQuestionAvailability} from '../lib/question-bank.mjs';
import {seedQuestions} from '../lib/practice.mjs';
type Case={id:string;title:string;organ:string;history:string;reference:string;images:string[];imageIds?:string[];version:number;authorized:boolean};
type Question={id:string;revision:number;owner:string;type:'single'|'short';prompt:string;options:{id:string;text:string}[];correctId:string;explanation:string;reference:string;rubric:{text:string;weight:number;dimension:string}[];caseSnapshot:Case|null;image:string;imageId:string;status:string;practiceOpen:boolean};
const dimensions=['临床信息整合','关键区域识别','形态学判断','诊断与鉴别','辅助检查规划'];
export default function QuestionBank({user,initialCaseId}:{user:Account;initialCaseId?:string}){
  const [cases,setCases]=useState<Case[]>([]),[rows,setRows]=useState<Question[]>([]),[draft,setDraft]=useState<Question|null>(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[preview,setPreview]=useState(false),[query,setQuery]=useState(''),[type,setType]=useState(''),[status,setStatus]=useState(''),[category,setCategory]=useState('');
  const exitDialog=useRef<HTMLDialogElement>(null),previewDialog=useRef<HTMLDialogElement>(null);
  const [decision,setDecision]=useState<'leave'|'confirm'|null>(null);
  const [locatedId,setLocatedId]=useState('');
  useEffect(()=>{if(!draft&&locatedId){const frame=requestAnimationFrame(()=>{const item=document.getElementById('question-'+locatedId);item?.focus();item?.scrollIntoView({block:'center'});});return()=>cancelAnimationFrame(frame);}},[draft,locatedId]);
  useEffect(()=>{if(decision)exitDialog.current?.showModal();else exitDialog.current?.close();},[decision]);
  useEffect(()=>{if(preview)previewDialog.current?.showModal();else previewDialog.current?.close();},[preview]);
  const changed=!!draft&&!rows.some(q=>JSON.stringify(q)===JSON.stringify(draft));
  const key='path-edu-question-draft-'+user.id;
  useEffect(()=>{
    const leave=(event:Event)=>{if(changed&&!window.confirm('本次修改尚未保存到题库。取消后可保存草稿；仍要离开？'))event.preventDefault();};
    const unload=(event:BeforeUnloadEvent)=>{if(changed){event.preventDefault();event.returnValue='';}};
    window.addEventListener('edu-before-leave',leave);window.addEventListener('beforeunload',unload);
    return()=>{window.removeEventListener('edu-before-leave',leave);window.removeEventListener('beforeunload',unload);};
  },[changed]);
  function blank(c:Case|null=null):Question{return {id:crypto.randomUUID(),revision:0,owner:user.id,type:'single',prompt:'',options:[{id:crypto.randomUUID(),text:''},{id:crypto.randomUUID(),text:''}],correctId:'',explanation:'',reference:'',rubric:[{text:'',weight:100,dimension:dimensions[3]}],caseSnapshot:c,image:c?.images[0]||'',imageId:c?(c.imageIds?.[0]||c.id+':0'):'',status:'draft',practiceOpen:false};}
  function reload(){setRows(seedQuestions(localStorage));}
  useEffect(()=>{try{const available=visibleLibraryCases(readLibraryStore(localStorage).cases,user) as Case[];setCases(available);reload();const saved=sessionStorage.getItem(key);if(saved){setDraft(JSON.parse(saved));setNotice('已恢复上次编辑内容');}else if(initialCaseId){const c=available.find(c=>c.id===initialCaseId);if(c)setDraft(blank(c));else setError('所选病例不可用');}}catch(e){setError((e as Error).message);}},[user.id,initialCaseId]);
  useEffect(()=>{if(!draft)return;try{sessionStorage.setItem(key,JSON.stringify(draft));}catch{setError('编辑内容暂存失败，请勿关闭页面');}},[draft,key]);
  function update(next:Partial<Question>){setDraft(d=>d?{...d,...next}:d);setNotice('');}
  function finish(){try{sessionStorage.removeItem(key);}catch{setError('无法清除暂存内容，请重试；本次编辑仍保留。');return false;}setDraft(null);setPreview(false);setDecision(null);setError('');return true;}
  function persist(confirm:boolean){if(!draft)return;try{const saved=saveQuestion(localStorage,draft,user,confirm);setDraft(saved);reload();if((confirm||decision==='leave')&&!finish())return;if(confirm){setQuery('');setType('');setStatus('');setCategory('');setLocatedId(saved.id);}setDecision(null);setNotice(confirm?'已确认入库，已定位到该题；练习尚未开放':`草稿已保存 · ${new Date().toLocaleTimeString()}`);setError('');}catch(e){setError((e as Error).message);}}
  const releaseFor=(q:Question):Question|undefined=>releasedQuestions(rows).find((r:Question)=>r.id===q.id);
  function availability(q:Question,action:string){try{const released=releaseFor(q);if(!released)return;setQuestionAvailability(localStorage,released,user,action);reload();setError('');}catch(e){setError((e as Error).message);}}
  const latest=rows.filter((q,i)=>q.owner===user.id&&!rows.slice(i+1).some(r=>r.id===q.id));
  const filtered=latest.filter(q=>(!type||q.type===type)&&(!status||q.status===status)&&(!category||q.caseSnapshot?.organ===category)&&`${q.prompt} ${q.caseSnapshot?.title}`.includes(query));
  function moveOption(index:number,step:number){if(!draft)return;const options=[...draft.options];[options[index],options[index+step]]=[options[index+step],options[index]];update({options});}
  return <section className="question-bank"><header className="library-header">{draft&&<Button className="page-back" onClick={()=>{if(changed)setDecision('leave');else finish();}}><span aria-hidden="true">←</span> 返回题库</Button>}<div><h1>{draft?'编辑题目':'题库与出题'}</h1></div>{draft?<div className="library-header-actions"><Button onClick={()=>setPreview(true)}>学生预览</Button></div>:<div className="library-header-actions"><Button variant="primary" onClick={()=>{const saved=sessionStorage.getItem(key);setDraft(saved?JSON.parse(saved):blank());}}>新建／继续出题</Button></div>}</header>
    {error&&<p className="account-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
    {!draft?<><div className="library-toolbar"><label>搜索题目<input value={query} onChange={e=>setQuery(e.target.value)}/></label><label>题型<select value={type} onChange={e=>setType(e.target.value)}><option value="">全部</option><option value="single">单选</option><option value="short">简答</option></select></label><label>状态<select value={status} onChange={e=>setStatus(e.target.value)}><option value="">全部</option><option value="draft">草稿</option><option value="confirmed">已确认</option><option value="disabled">已停用</option></select></label><label>部位<select value={category} onChange={e=>setCategory(e.target.value)}><option value="">全部</option>{libraryCategories.map(c=><option key={c}>{c}</option>)}</select></label></div>
      {!filtered.length&&<div className="account-card">暂无匹配题目，从图书馆选择片子开始出题。</div>}{filtered.length>0&&<div className="data-table" style={{'--cols':'minmax(0,2.4fr) .5fr 1.3fr .45fr .6fr auto'} as CSSProperties}><div className="head"><span>题干</span><span>题型</span><span>病例</span><span>版本</span><span>状态</span><span>操作</span></div>{filtered.map(q=><div id={'question-'+q.id} tabIndex={-1} key={q.id}><span><b title={q.prompt||'未命名草稿'}>{q.prompt||'未命名草稿'}</b>{q.status==='draft'&&releaseFor(q)?.status==='confirmed'&&<small>可用版本 v{releaseFor(q)?.revision} · {releaseFor(q)?.practiceOpen?'练习开放中':'练习未开放'}；当前草稿不影响旧版本。</small>}</span><span>{q.type==='single'?'单选':'简答'}</span><span>{q.caseSnapshot?.title||'未选病例'}</span><span>v{q.revision}</span><span>{{draft:'草稿',confirmed:'已确认',disabled:'已停用'}[q.status]}</span><div className="row-actions"><Button onClick={()=>{if(sessionStorage.getItem(key)&&!window.confirm('打开此题将替换暂存的编辑内容，继续？'))return;setDraft(q);setPreview(false);}}>编辑新版本</Button><Button onClick={()=>{if(sessionStorage.getItem(key)&&!window.confirm('复制此题将替换暂存编辑，继续？'))return;setDraft({...q,id:crypto.randomUUID(),revision:0,status:'draft',practiceOpen:false});}}>复制草稿</Button><Button disabled={releaseFor(q)?.status!=='confirmed'} onClick={()=>availability(q,'practice')}>{releaseFor(q)?.practiceOpen?'关闭练习':'开放练习'}</Button><Button disabled={!releaseFor(q)||releaseFor(q)?.status==='disabled'} variant="danger" onClick={()=>{if(window.confirm('停用后不可用于新练习或组卷，保留历史版本。继续？'))availability(q,'disable');}}>停用</Button></div></div>)}</div>}<p>已确认题可供后续组卷引用；练习开放不等于发放试卷。</p></>:<>
      <div className="question-editor"><aside className="account-card"><h2>1. 选择切片</h2><label>病例<select aria-label="病例" value={draft.caseSnapshot?.id||''} onChange={e=>{const c=cases.find(c=>c.id===e.target.value)||null;update({caseSnapshot:c,image:c?.images[0]||'',imageId:c?(c.imageIds?.[0]||c.id+':0'):''});}}><option value="">请选择</option>{cases.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label>{draft.caseSnapshot&&<><label>图片<select value={draft.imageId} onChange={e=>{const c=draft.caseSnapshot!;const i=c.images.findIndex((_,i)=>(c.imageIds?.[i]||c.id+':'+i)===e.target.value);update({imageId:e.target.value,image:c.images[i]});}}>{draft.caseSnapshot.images.map((_,i)=><option key={i} value={draft.caseSnapshot?.imageIds?.[i]||draft.caseSnapshot!.id+':'+i}>图片 {i+1}</option>)}</select></label><img src={draft.image} alt="所选病例图片"/><h3>病史</h3><p>{draft.caseSnapshot.history}</p><details><summary>教师参考依据</summary><p>{draft.caseSnapshot.reference||'未填写参考'}</p></details></>}</aside>
      <section className="account-card"><h2>2. 编辑题卡</h2><label>题型<select value={draft.type} onChange={e=>update({type:e.target.value as Question['type']})}><option value="single">单选题</option><option value="short">简答题</option></select></label>{draft.type==='single'&&<><Button disabled aria-describedby="ai-question-status">AI生成单选题</Button><small id="ai-question-status">服务未接入，请先手动编写</small></>}
      <label>题干<textarea aria-label="题干" value={draft.prompt} onChange={e=>update({prompt:e.target.value})}/></label>{draft.type==='single'?<><fieldset><legend>选项与正确答案</legend>{draft.options.map((o,i)=><div className="question-option" key={o.id}><label><input type="radio" name="correct" checked={draft.correctId===o.id} onChange={()=>update({correctId:o.id})}/>正确项 {i+1}</label><input aria-label={'选项 '+(i+1)} value={o.text} onChange={e=>update({options:draft.options.map(x=>x.id===o.id?{...x,text:e.target.value}:x)})}/><div className="question-option-tools" role="group" aria-label={'选项 '+(i+1)+' 操作'}><Button aria-label={'上移选项 '+(i+1)} title="上移" disabled={i===0} onClick={()=>moveOption(i,-1)}>↑</Button><Button aria-label={'下移选项 '+(i+1)} title="下移" disabled={i===draft.options.length-1} onClick={()=>moveOption(i,1)}>↓</Button><Button aria-label={'删除选项 '+(i+1)} onClick={()=>update({options:draft.options.filter(x=>x.id!==o.id),correctId:draft.correctId===o.id?'':draft.correctId})}>删除</Button></div></div>)}<Button onClick={()=>update({options:[...draft.options,{id:crypto.randomUUID(),text:''}]})}>添加选项</Button></fieldset><label>答案解析<textarea aria-label="答案解析" value={draft.explanation} onChange={e=>update({explanation:e.target.value})}/></label></>:<><label>参考答案<textarea value={draft.reference} onChange={e=>update({reference:e.target.value})}/></label><h3>评分点（合计100%）</h3>{draft.rubric.map((r,i)=><div className="question-rubric" key={i}><input aria-label={'评分点 '+(i+1)} value={r.text} onChange={e=>update({rubric:draft.rubric.map((x,n)=>n===i?{...x,text:e.target.value}:x)})}/><input aria-label={'权重百分比 '+(i+1)} type="number" min="1" max="100" value={r.weight} onChange={e=>update({rubric:draft.rubric.map((x,n)=>n===i?{...x,weight:Number(e.target.value)}:x)})}/><select aria-label={'能力维度 '+(i+1)} value={r.dimension} onChange={e=>update({rubric:draft.rubric.map((x,n)=>n===i?{...x,dimension:e.target.value}:x)})}>{dimensions.map(d=><option key={d}>{d}</option>)}</select><Button onClick={()=>update({rubric:draft.rubric.filter((_,n)=>n!==i)})}>删除</Button></div>)}<Button onClick={()=>update({rubric:[...draft.rubric,{text:'',weight:0,dimension:dimensions[3]}]})}>添加评分点</Button></>}
      </section></div><footer className="question-actions account-card"><span role="status">{changed?'有未保存修改':'已保存'}</span><Button disabled={!changed} onClick={()=>persist(false)}>保存草稿</Button><Button variant="primary" disabled={!changed&&draft.status==='confirmed'} onClick={()=>setDecision('confirm')}>确认入库</Button></footer>
      <dialog ref={previewDialog} className="account-card question-preview-dialog" aria-labelledby="question-preview-title" onCancel={()=>setPreview(false)} onClose={()=>setPreview(false)}><h2 id="question-preview-title">学生预览</h2><Button onClick={()=>setPreview(false)}>关闭预览</Button><p>{draft.caseSnapshot?.history}</p>{draft.image&&<img className="question-preview-image" src={draft.image} alt="学生预览切片"/>}<h3>{draft.prompt||'尚未填写题干'}</h3>{draft.type==='single'?draft.options.map(o=><label key={o.id}><input type="radio" name="student-preview" disabled/>{o.text}</label>):<textarea readOnly aria-label="简答作答预览" placeholder="请填写诊断、鉴别及必要的辅助检查思路"/>}</dialog>
    </>}
  <dialog ref={exitDialog} className="account-card question-decision-dialog" aria-labelledby="question-decision-title" onCancel={()=>setDecision(null)}><h2 id="question-decision-title">{decision==='leave'?'保留本次修改？':'确认题目入库？'}</h2><p>{decision==='leave'?'保存草稿后返回，或放弃本次未保存的修改。已入库版本和历史记录不会删除。':'请核对题干、答案和评分依据。入库不会自动开放练习或发放试卷。'}</p>{error&&<p role="alert">{error}</p>}<div className="question-actions"><Button onClick={()=>setDecision(null)}>继续编辑</Button>{decision==='leave'&&<Button variant="danger" onClick={finish}>放弃修改</Button>}<Button variant="primary" onClick={()=>persist(decision==='confirm')}>{decision==='leave'?'保存草稿并返回':'确认入库'}</Button></div></dialog>
  </section>;
}
